/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package adventofcode2022

import java.io.File

fun main() {
    val startTime = System.nanoTime()

    val file = File("./input/day01.txt")
    val calories = file.readLines()

    var index = 0
    val elvesInCalories = mutableListOf(0)
    for (line in calories) {
        if ("" == line) {
            index++
            elvesInCalories.add(0)
            continue
        }
        elvesInCalories[index] += line.toInt()
    }

    elvesInCalories.sortDescending()
    val totalTopThree = elvesInCalories.slice(IntRange(0, 2)).sum()

    println("Elf with most calories: ${elvesInCalories[0]}")
    println("Total top three: $totalTopThree")

    val endTime = System.nanoTime()
    println("Elapsed time: ${(endTime - startTime).toDouble() / 1000000000} sec")
}
