/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package adventofcode2022

import adventofcode2022.util.runWithStopwatch
import java.io.File
import java.nio.file.Paths

fun day01() {
    val path = Paths.get("").toAbsolutePath().toString()
    println("Working Directory = $path")

    val file = File("./input/day01.txt")
    val calories = file.readLines()

    var index = 0
    val elvesInCalories = mutableListOf(0)
    for (line in calories) {
        if ("" == line) {
            index++
            elvesInCalories.add(0)
            continue
        }
        elvesInCalories[index] += line.toInt()
    }

    elvesInCalories.sortDescending()
    val totalTopThree = elvesInCalories.slice(IntRange(0, 2)).sum()

    println("Elf with most calories: ${elvesInCalories[0]}")
    println("Total top three: $totalTopThree")
}

fun main() {
    runWithStopwatch { day01() }
}
